set(_CATKIN_CURRENT_PACKAGE "ICET")
set(ICET_VERSION "0.0.0")
set(ICET_MAINTAINER "derm <derm@todo.todo>")
set(ICET_PACKAGE_FORMAT "2")
set(ICET_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(ICET_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(ICET_BUILDTOOL_DEPENDS "catkin")
set(ICET_BUILDTOOL_EXPORT_DEPENDS )
set(ICET_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ICET_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ICET_TEST_DEPENDS )
set(ICET_DOC_DEPENDS )
set(ICET_URL_WEBSITE "")
set(ICET_URL_BUGTRACKER "")
set(ICET_URL_REPOSITORY "")
set(ICET_DEPRECATED "")