set(_CATKIN_CURRENT_PACKAGE "funtimes")
set(funtimes_VERSION "0.0.0")
set(funtimes_MAINTAINER "derm <derm@todo.todo>")
set(funtimes_PACKAGE_FORMAT "2")
set(funtimes_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(funtimes_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(funtimes_BUILDTOOL_DEPENDS "catkin")
set(funtimes_BUILDTOOL_EXPORT_DEPENDS )
set(funtimes_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(funtimes_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(funtimes_TEST_DEPENDS )
set(funtimes_DOC_DEPENDS )
set(funtimes_URL_WEBSITE "")
set(funtimes_URL_BUGTRACKER "")
set(funtimes_URL_REPOSITORY "")
set(funtimes_DEPRECATED "")